// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CodemirrorController from "./codemirror_controller"
application.register("codemirror", CodemirrorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)
